---
- name: Setup Prometheus
  hosts: your_target_host
  become: yes
  tasks:
    - name: Download Prometheus
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v2.8.1/prometheus-2.8.1.linux-amd64.tar.gz"
        dest: /tmp/prometheus-2.8.1.linux-amd64.tar.gz

    - name: Add Prometheus User
      user:
        name: prometheus
        shell: /bin/false
        system: yes

    - name: Create Directories and Set Ownership
      file:
        path: "{{ item }}"
        state: directory
        owner: prometheus
        group: prometheus
        mode: '0755'
      loop:
        - /etc/prometheus
        - /var/lib/prometheus

    - name: Extract Prometheus
      unarchive:
        src: /tmp/prometheus-2.8.1.linux-amd64.tar.gz
        dest: /tmp
        remote_src: yes

    - name: Rename Prometheus Package Directory
      command: mv /tmp/prometheus-2.8.1.linux-amd64 /tmp/prometheuspackage

    - name: Copy Prometheus and Promtool Binaries
      copy:
        src: "/tmp/prometheuspackage/{{ item }}"
        dest: /usr/local/bin/{{ item }}
        owner: prometheus
        group: prometheus
        mode: '0755'
      loop:
        - prometheus
        - promtool

    - name: Copy Consoles and Console Libraries
      copy:
        src: "/tmp/prometheuspackage/{{ item }}"
        dest: /etc/prometheus/{{ item }}
        owner: prometheus
        group: prometheus
        mode: '0755'
      loop:
        - consoles
        - console_libraries

    - name: Configure Prometheus
      template:
        src: prometheus.yml.j2
        dest: /etc/prometheus/prometheus.yml
        owner: prometheus
        group: prometheus
        mode: '0644'

    - name: Create systemd Unit File for Prometheus
      template:
        src: prometheus.service.j2
        dest: /etc/systemd/system/prometheus.service
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Start and Enable Prometheus Service
      service:
        name: prometheus
        state: started
        enabled: yes
